# Generated by Django 3.1 on 2020-08-17 18:46

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('intro', wagtail.core.blocks.RichTextBlock()), ('cover', wagtail.images.blocks.ImageChooserBlock()), ('body', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=250)), ('body', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'ol'])), ('another_page', wagtail.core.blocks.PageChooserBlock()), ('external_url', wagtail.core.blocks.URLBlock())])), ('image_gallery', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))], blank=True, null=True),
        ),
    ]
